<!-- nav.inc -->
            <nav class="header-nav">
                <ul>
                    <li><a href="index.php" class="active">Home</a></li>
                    <li><a href="jobs.php">Job Descriptions</a></li>
                    <li><a href="apply.php">Apply for a Job</a></li>
                    <li><a href="about.php">About Us</a></li>
                    <li><a href="mailto:info@cdssolutions.com.au">Contact Us</a></li>
                </ul>
            </nav>
        </div>
    </header>
